import "fake-indexeddb/auto";
import { IDBFactory } from "fake-indexeddb";
import {
  AdbWebCryptoCredentialManager,
  TangoIndexedDbStorage,
} from "@yume-chan/adb-credential-web";
import type { TangoKey } from "@yume-chan/adb-credential-web";
import { beforeEach, describe, expect, it } from "vitest";

// Guards Tango's IndexedDB key store, which `adb-manager.ts` uses for the RSA
// credential. In 3.0.0-beta.3 every operation threw ("callback must not be an
// async function"), so this is worth re-running on each `@yume-chan/*` bump.
// Runs against fake-indexeddb (an in-memory, spec-faithful IndexedDB). Each
// test starts from a fresh origin by swapping in a new factory.

async function collect(storage: TangoIndexedDbStorage): Promise<TangoKey[]> {
  const out: TangoKey[] = [];
  for await (const key of storage.load()) out.push(key);
  return out;
}

function open(name: string, version?: number, upgrade?: (db: IDBDatabase) => void) {
  return new Promise<IDBDatabase>((resolve, reject) => {
    const request = indexedDB.open(name, version);
    request.onupgradeneeded = () => upgrade?.(request.result);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

/** Create the "Tango" database at `version` holding `records`, as an earlier build left it. */
async function seed(version: number, records: unknown[]) {
  const db = await open("Tango", version, (db) => {
    db.createObjectStore("Authentication", { autoIncrement: true });
  });
  const transaction = db.transaction("Authentication", "readwrite");
  for (const record of records) transaction.objectStore("Authentication").add(record);
  await new Promise<void>((resolve, reject) => {
    transaction.oncomplete = () => resolve();
    transaction.onerror = () => reject(transaction.error);
  });
  db.close();
}

/** Raw view of the database. */
async function dump() {
  const db = await open("Tango");
  const names = Array.from(db.objectStoreNames);
  const records = await new Promise<unknown[]>((resolve, reject) => {
    const request = db
      .transaction("Authentication", "readonly")
      .objectStore("Authentication")
      .getAll();
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
  const version = db.version;
  db.close();
  return { version, names, records };
}

beforeEach(() => {
  globalThis.indexedDB = new IDBFactory();
});

describe("TangoIndexedDbStorage", () => {
  it("yields nothing on a fresh origin and creates its layout", async () => {
    const storage = new TangoIndexedDbStorage();
    expect(await collect(storage)).toEqual([]);
    expect(await dump()).toEqual({ version: 2, names: ["Authentication"], records: [] });
    await storage.close();
  });

  it("round-trips keys with their names, in insertion order, across operations", async () => {
    const storage = new TangoIndexedDbStorage();
    const a = new Uint8Array([1, 2, 3]);
    const b = new Uint8Array([4, 5]);
    await storage.save(a, "Android Device Manager");
    await storage.save(b, undefined);

    const keys = await collect(storage);
    expect(keys).toEqual([
      { privateKey: a, name: "Android Device Manager" },
      { privateKey: b, name: undefined },
    ]);
    expect(keys[0]?.privateKey).toBeInstanceOf(Uint8Array);
    // A further operation still works on the same instance.
    expect(await collect(storage)).toHaveLength(2);
    await storage.close();
  });

  it("reads keys the app's former own store wrote (same version-2 layout)", async () => {
    const key = new Uint8Array([7, 7]);
    await seed(2, [{ privateKey: key, name: "Android Device Manager" } satisfies TangoKey]);

    const storage = new TangoIndexedDbStorage();
    expect(await collect(storage)).toEqual([{ privateKey: key, name: "Android Device Manager" }]);
    await storage.close();
  });

  it("migrates Tango 2's version-1 layout, keeping the key bytes", async () => {
    const old1 = new Uint8Array([9, 8, 7, 6]);
    const old2 = new Uint8Array([5, 4]);
    await seed(1, [old1, old2]);

    const storage = new TangoIndexedDbStorage();
    expect(await collect(storage)).toEqual([
      { privateKey: old1, name: undefined },
      { privateKey: old2, name: undefined },
    ]);

    // New keys land beside the migrated ones.
    const fresh = new Uint8Array([1]);
    await storage.save(fresh, "Android Device Manager");
    expect((await collect(storage)).map((key) => key.privateKey)).toEqual([old1, old2, fresh]);
    await storage.close();
    expect((await dump()).version).toBe(2);
  });

  it("lets a fresh credential manager find a key generated by an earlier one", async () => {
    const first = new AdbWebCryptoCredentialManager(new TangoIndexedDbStorage(), "ADM");
    for await (const key of first.iterateKeys()) throw new Error(`unexpected key ${String(key)}`);
    await first.generateKey();
    await first.close();

    const second = new AdbWebCryptoCredentialManager(new TangoIndexedDbStorage(), "ADM");
    const keys = [];
    for await (const key of second.iterateKeys()) keys.push(key);
    expect(keys).toHaveLength(1);
    expect(keys[0]).not.toBeInstanceOf(Error);
    expect(keys[0]).toMatchObject({ name: "ADM" });
    await second.close();
  });
});
