name: 'Build'

on:
  push:
    tags: [ '*.*.*' ]

concurrency:
  group: docker-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: web
            context: web
          - image: proxy
            context: proxy
    uses: 'trexx/actions/.github/workflows/build.yml@136fc9f93210de08daf0b92ec7f3d89f12cc9031' # main
    secrets: 'inherit'
    permissions:
      contents: read
      packages: write
    with:
      prune_images: false
      context: ${{ matrix.context }}
      images: ghcr.io/${{ github.repository }}-${{ matrix.image }}