name: 'Build'

on:
  push:
    tags: [ '*.*.*' ]

concurrency:
  group: docker-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: web
            context: "{{defaultContext}}:web"
          - image: proxy
            context: "{{defaultContext}}:proxy"
    uses: 'trexx/actions/.github/workflows/build.yml@e29a8a55ae53f9a7440811be290f53470bea14aa' # main
    secrets: 'inherit'
    permissions:
      contents: read
      packages: write
    with:
      prune_images: false
      context: ${{ matrix.context }}
      images: ghcr.io/${{ github.repository }}-${{ matrix.image }}